version: 2.1
orbs:
  node: circleci/node@3.0.0
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm ci' # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          record: false # record results on Cypress Dashboard
          parallel: false # split all specs across machines
          parallelism: 1 # use 4 CircleCI machines to finish quickly
          group: 'all tests' # name this group "all tests" on the dashboard
          start: 'npm start' # start server before running tests
          spec: cypress/integration/first_test.spec.js